<?php
use JUser\Form\ChangeOtherPasswordForm;
use Laminas\View\Helper\Url;
?><h1>Warning...</h1>
<p><?php
    echo sprintf(
    $this->translate("The user will be notified of this change. Are you sure you want to change the password of '%s'?"),
    $this->user['username']
); ?></p>
<?php
/** @var Url $urlHelper */
$urlHelper = $this->plugin('url');
/** @var ChangeOtherPasswordForm $form */
$form = $this->form;
$form->setAttribute('action', $urlHelper('juser/user/change-password', [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('newCredential'));
echo $this->formRow($form->get('newCredentialVerify'));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo '&nbsp;';
?>
<a class="btn btn-default" href="<?= $urlHelper('juser'); ?>"><?= $this->translate('Cancel')?></a>
<?php echo $this->form()->closeTag(); ?>
